app:
  name: Shortner
  domain: localhost
  version: 0.1.1

services:
  shortening:
    name: shortening
    port: 3030
  
  redirecting:
    name: redirecting
    port: 3031
  
  analytics:
    name: analytics
    port: 3032