app:
  name: Shortner
  domain: localhost
  version: 0.1.1

services:
  shortening:
    name: shortening
    port: 3030
  
  redirecting:
    name: redirecting
    port: 3031
  
  analytics:
    name: analytics
    port: 3032
  
infrastructure:
  database:
    host: localhost
    port: 9042
    keyspace: shortner
    connTimeout: 1s

  redis:
    address: localhost:6379
    username: admin
    password: admin
    database: 1
  
  redisAnalytics:
    address: localhost:6380
    username: admin
    password: admin
    database: 1