version: '3.8'
name: "shortner"

services:
  cassandra:
    image: cassandra:5.0.8
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "local-cluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      HEAP_NEWSIZE: "128M"
      MAX_HEAP_SIZE: "512M"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./internal/migrations/cassandra:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  cassandra-init:
    image: cassandra:5.0.8
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./internal/migrations/cassandra:/init
    entrypoint: >
      bash -c "
        echo 'Running CQL init scripts...' &&
        for f in /init/*.cql; do
          echo \"Executing $$f\" && cqlsh cassandra -f $$f;
        done &&
        echo 'Init complete.'
      "
    restart: on-failure

  redis:
    image: redis:8.6
    restart: unless-stopped              
    ports:
      - "6379:6379"              
    volumes:
      - redis-data:/data
  
  redis-analytics:
    image: redis:8.6
    restart: unless-stopped              
    ports:
      - "6380:6379"              
    volumes:
      - redis-analytics-data:/data
    
  redis-insight:
    image: redis/redisinsight:3.2
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data
    depends_on:
      - redis
      - redis-analytics
  
  nginx-proxy:
    image: nginx:1.30.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
volumes:
  cassandra_data:
  redis-data:
  redis-analytics-data:
  redis-insight-data: