events {
	worker_connections 1024;
}
http {
    server {
        listen 80;
        server_name localhost;

        location /v1/shorten {
            proxy_pass http://host.docker.internal:3030;
			proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
        }

		location /s/ { # /s/{alias} -> /v1/redirect/{alias}
            rewrite ^/s/(.*)$ /v1/redirect/$1 break;
            proxy_pass http://host.docker.internal:3031;

            proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;

            mirror /analytics;

            mirror_request_body on;
        }
        
        location = /analytics {
            internal;
            rewrite ^ $request_uri; 
            rewrite ^/s/(.*)$ /v1/clicks/$1 break;
            proxy_pass http://host.docker.internal:3032;
            
            # Optional: Prevent delays on the main request if the shadow server is slow
            proxy_connect_timeout 200ms;
            proxy_read_timeout 200ms;
            proxy_pass_request_body on; 
        }
    }
}