events {
	worker_connections 1024;
}
http {
    server {
        listen 80;
        server_name localhost;

        location /v1/shorten {
            proxy_pass http://host.docker.internal:3030;
			proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
            
            limit_except POST {
                deny all;
            }

            proxy_set_header Content-Type $content_type;
            proxy_pass_request_body on;
        }

		location ~ ^/(?!v1/)(.+)$ { # /{alias} -> /v1/redirect/{alias}
            rewrite ^/(?!v1/)(.+)$ /v1/redirect/$1 break;
            proxy_pass http://host.docker.internal:3031;

            proxy_set_header Host $host;
        	proxy_set_header X-Real-IP $remote_addr;
        	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;

            # Optional: allow only GET for redirects
            limit_except GET {
                deny all;
            }
        }
    }
}